// 🔹 Navbar links
const navLinks = [
  { id: "home", title: "Home" },
  { id: "events", title: "Events" },
  { id: "team", title: "Team" },
];

const events = [
  // Existing Coding Event
  {
    title: "CodeQuest Hackathon",
    slug: "codequest-hackathon",
    category: "Coding",
    img: "https://i.im.ge/2023/10/22/t5Ggk1.charlesdeluvio-Lks7vei-eAg-unsplash-1.jpg?w=2048&q=10",
    desc: "An overnight hackathon where participants build innovative projects and solve real-world problems using technology.",
    prize: "₹50,000 + Goodies",
    deadline: "15th September 2025",
    venue: "Main Auditorium, Tech Campus",
    schedule: "16th September 2025, 9:00 AM – 17th September 2025, 9:00 AM",
    rules: [
      "Teams of 2-4 participants allowed.",
      "All projects must be built during the hackathon.",
      "Plagiarism will lead to disqualification.",
      "Judges’ decision will be final.",
    ],
    faq: [
      { q: "Do I need prior hackathon experience?", a: "No! Beginners are welcome. Mentors will guide you." },
      { q: "Will food and internet be provided?", a: "Yes, meals, snacks, and Wi-Fi will be available." },
    ],
    contacts: ["Rohan - +91 9876543210", "Aditi - +91 8765432109"],
    registerLink: "https://example.com/codequest",
    time: "To be announced",
  },
  // New Coding Events
  {
    title: "AI Code Clash",
    slug: "ai-code-clash",
    category: "Coding",
    img: "https://i.im.ge/2023/10/22/t5G7fa.max-bender-XIVDN9cxOVc-unsplash-2.jpg?w=2048&q=10",
    desc: "Build AI-driven applications to solve challenges in healthcare, education, or sustainability.",
    prize: "₹60,000 + Internship Opportunities",
    deadline: "13th September 2025",
    venue: "AI Lab, Tech Campus",
    schedule: "14th September 2025, 10:00 AM – 15th September 2025, 10:00 AM",
    rules: [
      "Teams of 2-5 participants.",
      "Use any AI/ML framework (e.g., TensorFlow, PyTorch).",
      "No pre-built solutions allowed.",
      "Presentation to judges required.",
    ],
    faq: [
      { q: "Can we use pre-trained models?", a: "Yes, but significant customization is expected." },
      { q: "Is cloud computing access provided?", a: "Yes, limited cloud credits will be provided." },
    ],
    contacts: ["Vikram - +91 9123456700", "Shalini - +91 8765432190"],
    registerLink: "https://example.com/aicodeclash",
    time: "To be announced",
  },
  {
    title: "Web Dev Showdown",
    slug: "web-dev-showdown",
    category: "Coding",
    img: "https://i.im.ge/2023/10/22/t55uKG.coding1-min.png?w=2048&q=10",
    desc: "Create responsive and innovative web applications under a time crunch.",
    prize: "₹30,000 + Certificates",
    deadline: "10th September 2025",
    venue: "Computer Lab A, Block B",
    schedule: "11th September 2025, 9:00 AM – 6:00 PM",
    rules: [
      "Teams of 1-3 participants.",
      "Use any web framework (React, Angular, etc.).",
      "Apps must be mobile-friendly.",
      "Judging based on functionality and UI.",
    ],
    faq: [
      { q: "Can we use templates?", a: "Basic templates are allowed, but originality is key." },
      { q: "Will hosting be provided?", a: "Yes, temporary hosting will be available." },
    ],
    contacts: ["Anil - +91 8899776644", "Tara - +91 7766554422"],
    registerLink: "https://example.com/webdevshowdown",
    time: "To be announced",
  },
  {
    title: "Code Golf Challenge",
    slug: "code-golf-challenge",
    category: "Coding",
    img: "https://i.im.ge/2023/10/22/t9QZRh.lorenzo-herrera-p0j-mE6mGo4-unsplash-1.jpg?w=2048&q=10",
    desc: "Solve algorithmic problems with the shortest possible code in your favorite programming language.",
    prize: "₹20,000 + Goodies",
    deadline: "17th September 2025",
    venue: "Lecture Hall 3, Block C",
    schedule: "18th September 2025, 1:00 PM – 5:00 PM",
    rules: [
      "Individual participation only.",
      "Solutions judged on code length and correctness.",
      "Any programming language allowed.",
      "No internet access during the event.",
    ],
    faq: [
      { q: "What languages are best for code golf?", a: "Python, C, or GolfScript are popular, but any language works." },
      { q: "Are there practice problems?", a: "Yes, sample problems will be shared post-registration." },
    ],
    contacts: ["Suresh - +91 9988776633", "Lila - +91 7766443311"],
    registerLink: "https://example.com/codegolf",
    time: "To be announced",
  },
  // Existing Robotics Events
  {
    title: "Robo Race",
    slug: "robo-race",
    category: "Robotics",
    img: "https://i.im.ge/2023/10/23/tjfSZ6.apryan-widodo-LVKVvuhq5r4-unsplash-1.jpg?w=2048&q=10",
    desc: "A thrilling race where autonomous robots compete on a challenging obstacle track.",
    prize: "₹30,000 + Trophies",
    deadline: "18th September 2025",
    venue: "Mechanical Workshop Ground",
    schedule: "20th September 2025, 11:00 AM – 4:00 PM",
    rules: [
      "Teams of 2-3 allowed.",
      "Robots must be built prior to the event.",
      "Robots must complete the track within time limit.",
    ],
    faq: [
      { q: "What type of robots are allowed?", a: "Wheeled robots only, no drones." },
      { q: "Can we use ready-made kits?", a: "Yes, but innovation will be rewarded." },
    ],
    contacts: ["Manav - +91 8899776655", "Priya - +91 9988223344"],
    registerLink: "https://example.com/roborace",
    time: "To be announced",
  },
  {
    title: "Line Follower Challenge",
    slug: "line-follower-challenge",
    category: "Robotics",
    img: "https://i.im.ge/2023/10/23/tjfgGG.marilia-castelli-wCVNhNnI-2s-unsplash-1.jpg?w=2048&q=10",
    desc: "Robots must follow a track of black-and-white lines with maximum precision and speed.",
    prize: "₹15,000 + Medals",
    deadline: "14th September 2025",
    venue: "Robotics Lab, Block C",
    schedule: "15th September 2025, 2:00 PM – 6:00 PM",
    rules: [
      "Teams of max 3 participants.",
      "Robots must autonomously follow the line.",
      "Manual control is not allowed.",
    ],
    faq: [
      { q: "Can I use sensors?", a: "Yes, IR or LDR sensors are recommended." },
      { q: "What is the track size?", a: "Track details will be revealed on the event day." },
    ],
    contacts: ["Karan - +91 7766554433", "Simran - +91 8877665544"],
    registerLink: "https://example.com/linefollower",
    time: "To be announced",
  },
  // New Robotics Events
  {
    title: "Drone Obstacle Course",
    slug: "https://i.im.ge/2023/10/23/tjkiEx.aditya-chinchure-GKkm9OXObCM-unsplash-1.jpg?w=2048&q=10",
    category: "Robotics",
    img: "/images/dronecourse.jpg",
    desc: "Navigate drones through a complex obstacle course with precision and speed.",
    prize: "₹35,000 + Certificates",
    deadline: "19th September 2025",
    venue: "Outdoor Arena, Tech Campus",
    schedule: "21st September 2025, 12:00 PM – 5:00 PM",
    rules: [
      "Teams of 1-2 participants.",
      "Drones must be pre-tested for safety.",
      "Manual control allowed, autonomous for bonus points.",
    ],
    faq: [
      { q: "Can we use custom-built drones?", a: "Yes, but they must meet safety standards." },
      { q: "Is there a weight limit?", a: "Max 2 kg for drones." },
    ],
    contacts: ["Vishal - +91 8877663322", "Riya - +91 9988775544"],
    registerLink: "https://example.com/dronecourse",
    time: "To be announced",
  },
  {
    title: "Robo Sumo",
    slug: "robo-sumo",
    category: "Robotics",
    img: "https://i.im.ge/2023/10/23/tjf4DX.Screenshot-2023-10-23-080427-1.png?w=2048&q=10",
    desc: "Build robots to push opponents out of a circular arena in a sumo-style competition.",
    prize: "₹25,000 + Trophies",
    deadline: "16th September 2025",
    venue: "Mechanical Lab, Block A",
    schedule: "17th September 2025, 11:00 AM – 4:00 PM",
    rules: [
      "Teams of 2-3 participants.",
      "Robots must weigh under 3 kg.",
      "No intentional damage to opponent robots.",
    ],
    faq: [
      { q: "Can we modify robots between rounds?", a: "Yes, within 5-minute breaks." },
      { q: "Are there size restrictions?", a: "Max 20x20 cm base." },
    ],
    contacts: ["Nikhil - +91 7766445599", "Anita - +91 8877664433"],
    registerLink: "https://example.com/robosumo",
    time: "To be announced",
  },
  // Existing Astro Events
  {
    title: "Stargazing Night",
    slug: "stargazing-night",
    category: "Astro",
    img: "https://cdn.britannica.com/60/190760-131-F1576E0B/space-background-telescope-silhouette-NASA-image-elements.jpg?w=2048&q=10",
    desc: "An evening with telescopes under the night sky, guided by experts in astronomy.",
    prize: "Participation Certificates",
    deadline: "16th September 2025",
    venue: "Astronomy Club Terrace",
    schedule: "18th September 2025, 8:00 PM – Midnight",
    rules: [
      "Individual and groups allowed.",
      "No flash photography near telescopes.",
    ],
    faq: [
      { q: "Do I need to bring a telescope?", a: "No, telescopes will be provided." },
      { q: "Is prior knowledge required?", a: "No, experts will explain everything." },
    ],
    contacts: ["Rahul - +91 8899776655", "Sneha - +91 7788994455"],
    registerLink: "https://example.com/stargazing",
    time: "To be announced",
  },
  {
    title: "Astro Quiz",
    slug: "astro-quiz",
    category: "Astro",
    img: "https://www.shutterstock.com/image-vector/cosmic-convergence-astronauts-journey-through-600nw-2315587451.jpg?w=2048&q=10",
    desc: "Quiz competition on space science, astronomy, and astrophysics.",
    prize: "₹8,000 + Certificates",
    deadline: "11th September 2025",
    venue: "Physics Lecture Hall",
    schedule: "12th September 2025, 2:00 PM – 5:00 PM",
    rules: [
      "Teams of 2 allowed.",
      "No internet devices during quiz.",
      "Quiz will have MCQs and buzzer round.",
    ],
    faq: [
      { q: "Is the quiz only for science students?", a: "No, open for all participants." },
      { q: "Will there be a negative marking?", a: "Yes, -1 for every wrong answer." },
    ],
    contacts: ["Pooja - +91 6655778899", "Adarsh - +91 7766443322"],
    registerLink: "https://example.com/astroquiz",
    time: "To be announced",
  },
  // New Astro Events
  {
    title: "Rocket Design Challenge",
    slug: "rocket-design-challenge",
    category: "Astro",
    img: "https://i.im.ge/2023/10/23/tjfV2y.hung-nguyen-phi-5Bo6OfopSi0-unsplash-1.jpg?w=2048&q=10",
    desc: "Design and simulate a model rocket for a hypothetical space mission.",
    prize: "₹20,000 + Certificates",
    deadline: "15th September 2025",
    venue: "Aerospace Lab, Block D",
    schedule: "16th September 2025, 10:00 AM – 4:00 PM",
    rules: [
      "Teams of 2-4 participants.",
      "Use simulation software provided.",
      "Designs judged on feasibility and creativity.",
    ],
    faq: [
      { q: "Do we need aerospace knowledge?", a: "Basic guidance will be provided." },
      { q: "Can we use physical models?", a: "Only digital simulations are required." },
    ],
    contacts: ["Siddhant - +91 8877662211", "Kavya - +91 9988773322"],
    registerLink: "https://example.com/rocketdesign",
    time: "To be announced",
  },
  {
    title: "Astro Photography Workshop",
    slug: "astro-photography-workshop",
    category: "Astro",
    img: "https://hips.hearstapps.com/pop.h-cdn.co/assets/17/11/2560x1920/sd-aspect-1489610446-milkyway.jpg?resize=768:*",
    desc: "Learn to capture stunning images of celestial bodies with expert guidance.",
    prize: "Certificates + Feature in Club Magazine",
    deadline: "17th September 2025",
    venue: "Astronomy Club Terrace",
    schedule: "19th September 2025, 7:00 PM – 10:00 PM",
    rules: [
      "Bring your own camera or use provided equipment.",
      "Follow instructor guidelines for telescope use.",
      "Submit one photo for exhibition.",
    ],
    faq: [
      { q: "Do I need a DSLR?", a: "No, mobile cameras with manual settings are fine." },
      { q: "Is prior experience needed?", a: "No, the workshop is beginner-friendly." },
    ],
    contacts: ["Arnav - +91 7766442288", "Tanya - +91 8877663399"],
    registerLink: "https://example.com/astrophotography",
    time: "To be announced",
  },
  // Existing Dept Event
  {
    title: "Design Sprint",
    slug: "design-sprint",
    category: "Dept",
    img: "/images/designsprint.jpg",
    desc: "A fast-paced event focused on UI/UX problem solving and creative design thinking challenges.",
    prize: "₹20,000 + Certificates",
    deadline: "10th September 2025",
    venue: "Innovation Lab, Block B",
    schedule: "12th September 2025, 10:00 AM – 6:00 PM",
    rules: [
      "Individual participation only.",
      "Submit all design assets before the deadline.",
      "Respect the theme provided at the event start.",
    ],
    faq: [
      { q: "What tools can I use?", a: "You can use Figma, Adobe XD, Photoshop, or any design tool." },
      { q: "Will I get feedback?", a: "Yes, judges will provide constructive feedback after results." },
    ],
    contacts: ["Neha - +91 9123456789", "Arjun - +91 9988776655"],
    registerLink: "https://example.com/designsprint",
    time: "To be announced",
  },
  // Reassign Photography Contest to Dept (Creative/Design)
  {
    title: "Photography Contest",
    slug: "photography-contest",
    category: "Dept",
    img: "/images/photography.jpg",
    desc: "Capture and share your best shots around the theme 'Innovation and Nature'.",
    prize: "₹15,000 + Goodies",
    deadline: "12th September 2025",
    venue: "Exhibition Hall",
    schedule: "13th September 2025, 11:00 AM – 3:00 PM",
    rules: [
      "Individual participation only.",
      "Photos must be original and unedited.",
      "Max 3 submissions per participant.",
    ],
    faq: [
      { q: "Can I use DSLR or mobile?", a: "Yes, any camera device is allowed." },
      { q: "Do I need to print photos?", a: "Yes, bring printed copies for exhibition." },
    ],
    contacts: ["Kabir - +91 6655443322", "Ananya - +91 7766889900"],
    registerLink: "https://example.com/photography",
    time: "To be announced",
  },
  // New Dept Events
  {
    title: "Logo Design Battle",
    slug: "logo-design-battle",
    category: "Dept",
    img: "/images/logodesign.jpg",
    desc: "Create a unique logo for a fictional startup based on a given brief.",
    prize: "₹18,000 + Certificates",
    deadline: "14th September 2025",
    venue: "Design Studio, Block B",
    schedule: "15th September 2025, 11:00 AM – 5:00 PM",
    rules: [
      "Individual participation only.",
      "Submit vector files in SVG/PNG format.",
      "Follow the provided brand guidelines.",
    ],
    faq: [
      { q: "Can I use Canva?", a: "Yes, but professional tools like Illustrator are preferred." },
      { q: "Will the brief be shared early?", a: "Brief will be revealed at the event start." },
    ],
    contacts: ["Rhea - +91 7766558877", "Soham - +91 8877661122"],
    registerLink: "https://example.com/logodesign",
    time: "To be announced",
  },
  {
    title: "Poster Making Competition",
    slug: "poster-making-competition",
    category: "Dept",
    img: "/images/postermaking.jpg",
    desc: "Design eye-catching posters for a tech fest theme using digital or traditional media.",
    prize: "₹12,000 + Goodies",
    deadline: "11th September 2025",
    venue: "Art Room, Block E",
    schedule: "12th September 2025, 1:00 PM – 4:00 PM",
    rules: [
      "Individual or teams of 2 allowed.",
      "Digital or hand-drawn posters accepted.",
      "Max size: A3 for physical, 1080p for digital.",
    ],
    faq: [
      { q: "Can I submit both digital and physical?", a: "No, choose one medium per entry." },
      { q: "Is there a theme?", a: "Yes, announced at the event start." },
    ],
    contacts: ["Ishaan - +91 9988774433", "Nidhi - +91 7766445566"],
    registerLink: "https://example.com/postermaking",
    time: "To be announced",
  },
  // Other Hackathons (Reassign Esports Arena and LAN Party, add new ones)
  {
    title: "Esports Arena",
    slug: "esports-arena",
    category: "Other Hackathons",
    img: "/images/esports.jpg",
    desc: "Compete in popular esports titles including Valorant, BGMI, and FIFA in a hackathon-style tournament.",
    prize: "₹40,000 + Gaming Accessories",
    deadline: "19th September 2025",
    venue: "Computer Science Lab, Block D",
    schedule: "21st September 2025, 10:00 AM – 10:00 PM",
    rules: [
      "Team sizes depend on the game.",
      "Cheating or hacks will result in disqualification.",
      "Follow fair play policies.",
    ],
    faq: [
      { q: "Do I need my own setup?", a: "Basic PCs will be provided. You may bring your peripherals." },
      { q: "Can we register for multiple games?", a: "Yes, but schedules may overlap." },
    ],
    contacts: ["Akash - +91 8899221100", "Sanya - +91 7778889990"],
    registerLink: "https://example.com/esports",
    time: "To be announced",
  },
  {
    title: "LAN Party",
    slug: "lan-party",
    category: "Other Hackathons",
    img: "/images/lanparty.jpg",
    desc: "A retro-style LAN gaming hackathon featuring CS 1.6, NFS, and more.",
    prize: "₹10,000 + Certificates",
    deadline: "13th September 2025",
    venue: "Innovation Hub, Block E",
    schedule: "14th September 2025, 4:00 PM – 10:00 PM",
    rules: [
      "Teams of 5 for CS 1.6.",
      "No external hacks or mods allowed.",
      "Respect gaming ethics.",
    ],
    faq: [
      { q: "Do I need to bring my laptop?", a: "No, systems will be provided." },
      { q: "Which games are featured?", a: "CS 1.6, NFS Most Wanted, Blur, and more." },
    ],
    contacts: ["Ritika - +91 7766552233", "Aryan - +91 6677889900"],
    registerLink: "https://example.com/lanparty",
    time: "To be announced",
  },
  {
    title: "IoT Hackathon",
    slug: "iot-hackathon",
    category: "Other Hackathons",
    img: "/images/iothackathon.jpg",
    desc: "Develop innovative IoT solutions for smart homes, cities, or agriculture.",
    prize: "₹45,000 + Hardware Kits",
    deadline: "18th September 2025",
    venue: "Electronics Lab, Block C",
    schedule: "19th September 2025, 9:00 AM – 20th September 2025, 9:00 AM",
    rules: [
      "Teams of 2-4 participants.",
      "Prototypes must include IoT hardware.",
      "Provide a working demo to judges.",
    ],
    faq: [
      { q: "Will hardware be provided?", a: "Basic kits like Raspberry Pi will be available." },
      { q: "Can we use cloud platforms?", a: "Yes, AWS IoT or similar platforms are allowed." },
    ],
    contacts: ["Ravi - +91 8877665544", "Pallavi - +91 9988772211"],
    registerLink: "https://example.com/iothackathon",
    time: "To be announced",
  },
  {
    title: "Blockchain Innovate",
    slug: "blockchain-innovate",
    category: "Other Hackathons",
    img: "/images/blockchain.jpg",
    desc: "Build decentralized applications using blockchain technology for finance, supply chain, or social impact.",
    prize: "₹50,000 + Certificates",
    deadline: "16th September 2025",
    venue: "Computer Lab B, Block D",
    schedule: "17th September 2025, 10:00 AM – 18th September 2025, 10:00 AM",
    rules: [
      "Teams of 2-4 participants.",
      "Use any blockchain platform (Ethereum, Solana, etc.).",
      "Smart contracts must be functional.",
    ],
    faq: [
      { q: "Do we need blockchain experience?", a: "Basic tutorials will be provided pre-event." },
      { q: "Can we use testnets?", a: "Yes, testnets are recommended for demos." },
    ],
    contacts: ["Sameer - +91 7766446677", "Aisha - +91 8877669988"],
    registerLink: "https://example.com/blockchain",
    time: "To be announced",
  },
  {
    title: "AR/VR Hackathon",
    slug: "ar-vr-hackathon",
    category: "Other Hackathons",
    img: "/images/arvrhackathon.jpg",
    desc: "Create immersive augmented or virtual reality experiences for education or entertainment.",
    prize: "₹40,000 + VR Headsets",
    deadline: "14th September 2025",
    venue: "Multimedia Lab, Block E",
    schedule: "15th September 2025, 9:00 AM – 16th September 2025, 9:00 AM",
    rules: [
      "Teams of 2-5 participants.",
      "Use AR/VR tools like Unity or Unreal Engine.",
      "Demos must run on provided hardware.",
    ],
    faq: [
      { q: "Do we need AR/VR devices?", a: "Basic headsets will be provided." },
      { q: "Can we focus on AR only?", a: "Yes, AR or VR projects are both acceptable." },
    ],
    contacts: ["Kunal - +91 9988773344", "Mira - +91 7766448899"],
    registerLink: "https://example.com/arvrhackathon",
    time: "To be announced",
  },
  // Cultural Event (Excluded as it doesn't fit requested categories, but kept for completeness)
  {
    title: "Talent Show",
    slug: "talent-show",
    category: "Cultural",
    img: "/images/talentshow.jpg",
    desc: "Showcase your music, dance, or acting talent on stage in front of a live audience.",
    prize: "₹25,000 + Certificates",
    deadline: "17th September 2025",
    venue: "Open Air Theatre",
    schedule: "19th September 2025, 5:00 PM – 10:00 PM",
    rules: [
      "Individual and group performances allowed.",
      "Time limit: 5 minutes per act.",
      "Offensive content not allowed.",
    ],
    faq: [
      { q: "Can I perform in multiple categories?", a: "Yes, but time slots will be limited." },
      { q: "Are musical instruments provided?", a: "Basic setup will be provided, bring your instruments if needed." },
    ],
    contacts: ["Meera - +91 7788990011", "Dev - +91 8899001122"],
    registerLink: "https://example.com/talentshow",
    time: "To be announced",
  },
];
// 🔹 Grouped by category for tabs in Event.jsx
const eventsData = events.reduce((acc, ev) => {
  if (!acc[ev.category]) acc[ev.category] = [];
  acc[ev.category].push(ev);
  return acc;
}, {});

export { navLinks, eventsData, events };