// 🔹 Navbar links
const navLinks = [
  { id: "home", title: "Home" },
  { id: "events", title: "Events" },
  { id: "team", title: "Team" },
  { id: "buy-merch", title: "Buy Merch" },
];

const events = [
  // Coding Event
  {
    title: "Hackathon",
    slug: "hackathon",
    category: "Coding",
    img: "/events/coding/hackathon.jpg",
    desc: "Get ready for an adrenaline-filled coding marathon with our Hackathon, where creativity meets technology! This is your chance to transform innovative ideas into real-world solutions within a limited time frame.Participants will collaborate in teams to brainstorm, design, and develop projects that tackle real-life problems. Whether it’s web development, AI, IoT, or app building — this hackathon is all about pushing boundaries and bringing ideas to life.",
    prize: "Exciting Prizes",
    venue: "CS Lab, A Block",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Prem Kumar Gupta - b22cs026@nitm.ac.in",
      "Shashank Umar Vaishy - b23cs019@nitm.ac.in",
      "Charity Rymbai - b23me010@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/rhgru4aRH8CCC7519",
    rulebookLink:
      "https://drive.google.com/file/d/1pN0ynway3Z3e7fRLHoA6CVTN8BPnxxoQ/view?usp=drive_link",
  },
  {
    title: "Coding Contest",
    slug: "coding-contest",
    category: "Coding",
    img: "/events/coding/codeconquest.png",
    desc: "Step into the battlefield of logic and algorithms with Code Conquest, the ultimate coding challenge designed to test your problem-solving skills, speed, and precision. Whether you’re a beginner or a seasoned programmer, this event pushes you to think critically and code efficiently under pressure.",
    prize: "Exciting Prizes",
    venue: "CS Lab, A Block",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Mrinmoy Maji - b22cs036@nitm.ac.in",
      "Ankit Raj - b23ec012@nitm.ac.in",
      "Abhay Kumar - b23ec022@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/Mcjd2Mpw6KTSDeKi9",
    rulebookLink:
      "https://drive.google.com/file/d/1m6zcpyZD0qpcx4FU2cGzIF53ky2mGsk0/view?usp=drive_link",
  },
  {
    title: "Capture The Flag",
    slug: "capture-the-flag",
    category: "Coding",
    img: "/events/coding/capturetheflag.jpg",
    desc: "Step into the world of cybersecurity with Capture The Flag (CTF) — an intense, challenge-based competition where participants solve security puzzles, uncover hidden vulnerabilities, and capture digital “flags” to score points.From cryptography and web exploitation to reverse engineering and forensics, this event is designed to test your hacking mindset, analytical thinking, and technical skills in a fun and competitive environment.",
    prize: "Exciting Prizes",
    venue: "CS Lab, A Block",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Manish Prasad Gupta - b22cs007@nitm.ac.in",
      "Austin Joel Dympep - b23cs035@nitm.ac.in",
      "Arunoday Tiwari - b23ec009@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/pToTjhjDgCyP3fHf9",
    rulebookLink:
      "https://drive.google.com/file/d/13lWHAieu5P3LlopPQeKtAtAdgwEEuJkm/view?usp=drive_link",
  },
  {
    title: "Blind Folded Coding",
    slug: "blind-folded-coding",
    category: "Coding",
    img: "/events/coding/blindfoldedcoding.webp",
    desc: "Think you truly know coding? Put your skills to the ultimate test in Blindfolded Coding — a thrilling challenge where participants must write code without seeing their screens!.This event pushes your logical thinking, syntax mastery, and memory to the limit. With vision taken away, only your understanding of programming concepts and keyboard familiarity will guide you to victory.",
    prize: "Exciting Prizes",
    venue: "CS Lab, A Block",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Mrinmoy Maji - b22cs036@nitm.ac.in",
      "Ankit Raj - b23ec012@nitm.ac.in",
      "Abhay Kumar - b23ec022@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/Vub72ZYazdhDb6ao7",
    rulebookLink:
      "https://drive.google.com/file/d/1golCFEnH6a12TGjKlS5cD6CTsYw-Y53d/view?usp=drive_link",
  },
  {
    title: "Relay Typing Competition",
    slug: "relay-typing-competition",
    category: "Coding",
    img: "/events/coding/relaytyping.webp",
    desc: "Speed meets teamwork in the Relay Typing Competition! Participants compete in teams where each member contributes sequentially to complete a given typing or coding task. Accuracy, coordination, and speed are the keys to victory in this fun yet competitive event.",
    prize: "Exciting Prizes",
    venue: "CS Lab, A Block",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Prem Kumar Gupta - Convenor",
      "Aryan Raj - Coordinator",
      "Khushi Kumari - Coordinator",
    ],
    registerLink: "https://forms.gle/rpzRCiwccHiBNuSo7",
    rulebookLink:
      "https://drive.google.com/file/d/1ByM22JZVa3gbX8eGVMjNlx6VNRWQ0p1g/view?usp=drive_link",
  },

  {
    title: "Tech Dumb Charades",
    slug: "tech-dumb-charades",
    category: "Coding",
    img: "/events/coding/techcharades.jpg",
    desc: "A fun twist on the classic game! Tech Dumb Charades challenges participants to guess technical terms, technologies, or concepts through gestures and acting — no words allowed. It's a perfect blend of tech knowledge, creativity, and entertainment.",
    prize: "Exciting Prizes",
    venue: "CS Lab, A Block",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Karipireddy Surya Teja Gopal Reddy - b22cs022@nitm.ac.in",
      "Jishnu Duhan - b23cs037@nitm.ac.in",
      "Shashank Umar Vaishy - b23cs019@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/bjokzKeJ85oBde3n6",
    rulebookLink:
      "https://drive.google.com/file/d/1HmEzD4GZKSFfKSp7VDifUtYwDU-3ztOj/view?usp=drive_link",
  },

  {
    title: "Game of Codes",
    slug: "game-of-codes",
    category: "Coding",
    img: "/events/coding/gameofcodes.webp",
    desc: "Enter the ultimate coding arena with Game of Codes! Participants will battle through multiple rounds of coding challenges, debugging tasks, and logic puzzles. Only the sharpest minds will survive till the end and claim the throne.",
    prize: "Exciting Prizes",
    venue: "CS Lab, A Block",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Prem Kumar Gupta - b22cs026@nitm.ac.in",
      "Charity Rymbai - b23me010@nitm.ac.in",
      "Aryan Raj - b23ec042@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/HQU5fYqXP83v9ncW8",
    rulebookLink:
      "https://drive.google.com/file/d/1UkUeoQbWAIGY_vyTbpvkwqTKNMCFHlmS/view?usp=drive_link",
  },

  {
    title: "404 Killer Not Found",
    slug: "404-killer-not-found",
    category: "Coding",
    img: "/events/coding/404killer.jpeg",
    desc: "Errors are everywhere — can you eliminate them? 404 Killer Not Found is a debugging-focused event where participants must identify and fix bugs in given code snippets. Speed, precision, and deep understanding of programming concepts will determine the ultimate bug slayer.",
    prize: "Exciting Prizes",
    venue: "CS Lab, A Block",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "T Vikram Rathod - b22cs033@nitm.ac.in",
      "Jishnu Duhan - b23cs037@nitm.ac.in",
      "Austin Joel Dympep - b23cs035@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/Cik9URfnm93c726o7",
    rulebookLink:
      "https://drive.google.com/file/d/1zYEDwQOF8Epa_mluQY75aHi_3UB5HKLj/view?usp=drive_link",
  },

  {
    title: "Treasure Hunt",
    slug: "treasure-hunt",
    category: "Coding",
    img: "/events/coding/treasurehunt.jpg",
    desc: "Embark on an exciting journey of clues, puzzles, and hidden challenges in the Treasure Hunt! Participants must solve technical riddles and coding-based hints to progress through stages and uncover the final treasure.",
    prize: "Exciting Prizes",
    venue: "Campus Wide",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Prem Kumar Gupta - b22cs026@nitm.ac.in",
      "Shashank Umar Vaishy - b23cs019@nitm.ac.in",
      "Khushi Kumari - b23ec008@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/tALHtmmHLtvNTT5g9",
    rulebookLink:
      "https://drive.google.com/file/d/1FbKqeor9yAdPxQY10yGBSY6uMJZwfjuZ/view?usp=drive_link",
  },

  {
    title: "Smart Machine",
    slug: "smart-machine",
    category: "Coding",
    img: "/events/coding/smartmachine.jpeg",
    desc: "Dive into the world of intelligent systems with Smart Machine! This event focuses on building or conceptualizing smart solutions using AI, ML, or automation. Participants will showcase innovative ideas that simulate real-world intelligent behavior.",
    prize: "Exciting Prizes",
    venue: "CS Lab, A Block",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Satyajeet Rai - b22ec021@nitm.ac.in",
      "Ayush Kumar Singh - b23ec003@nitm.ac.in",
      "Chuncha Hemchand - b23cs020@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/NthY1Ev8sAs8vh6U7",
    rulebookLink:
      "https://drive.google.com/file/d/1Fg9LBAIzNhZLIi5oEigc7UJwwjIxHOn2/view?usp=drive_link",
  },

  {
    title: "Neural Quest",
    slug: "neural-quest",
    category: "Coding",
    img: "/events/coding/neuralquest.jpg",
    desc: "Challenge your knowledge of artificial intelligence and neural networks in Neural Quest! This event includes quizzes, problem-solving, and practical tasks related to AI/ML concepts, testing both theoretical understanding and application skills.",
    prize: "Exciting Prizes",
    venue: "CS Lab, A Block",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "T Vikram Rathore - b22cs033@nitm.ac.in",
      "Jishnu Duhan - b23cs037@nitm.ac.in",
      "Ayush Kumar Singh - b23ec003@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/HrZxoS4MGMHpijgLA",
    rulebookLink:
      "https://drive.google.com/file/d/1qGDf0jo2VM6fNQQ-yGNq7FshBrORZv5G/view?usp=drive_link",
  },

  // Robotics Events
  {
    title: "Robo Rumble",
    slug: "robo-rumble",
    category: "Robotics",
    img: "/events/robotics/roborumble.jpeg",
    desc: "Gear up for Robo Rumble — an electrifying battle of bots where machines clash in an arena of destruction and strategy. Design and control your robot to outmaneuver and outlast your opponents in this ultimate test of engineering and combat skills.",
    prize: "Exciting Prizes",
    venue: "Between C & D Block || Lecture Hall Complex",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Shivam Kumar - b22me011@nitm.ac.in",
      "Rahul Kumar - Convenor",
      "Akash Shah - b23me008@nitm.ac.in",
      "Sachin Chaurasia - b23ee010@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/aRTdqwu7fgUGXgKK9",
    rulebookLink:
      "https://drive.google.com/file/d/1A2HTeTnLjj5S_KsPOodj4n1Pu_yvfKIM/view?usp=drive_link",
  },

  {
    title: "Goal Against Time",
    slug: "goal-against-time",
    category: "Robotics",
    img: "/events/robotics/goalagainsttime.jpg",
    desc: "Precision meets speed in Goal Against Time! Participants must design robots capable of completing specific tasks within a limited time frame. Efficiency, accuracy, and quick thinking are the keys to winning.",
    prize: "Exciting Prizes",
    venue: "Robotics Arena",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Aditya Kumar Pandey - b22me018@nitm.ac.in",
      "Himanshu Kumar Jha - b22me027@nitm.ac.in",
      "Vishnu Kumar - b23ee014@nitm.ac.in",
      "Akshaj Sunil - b23me020@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/B2Gqw9UkGrqDwWAY7",
    rulebookLink:
      "https://drive.google.com/file/d/1N12oqlPEpnqmzlds9Io0XBuDcPo3tVqV/view?usp=drive_link",
  },

  {
    title: "Humanoid",
    slug: "humanoid",
    category: "Robotics",
    img: "/events/robotics/humanoid.jpeg",
    desc: "Experience the future with Humanoid — an event focused on designing and showcasing human-like robots. Participants will demonstrate innovation in movement, balance, and interaction, pushing the boundaries of robotics.",
    prize: "Exciting Prizes",
    venue: "Robotics Arena",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Debashish Nayak - b22ec030@nitm.ac.in",
      "Sanapala Rahul - b22ee010@nitm.ac.in",
      "Adharsh Barman - b23ee005@nitm.ac.in",
      "Saksham Singhania - b23ce026@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/dJc4yfxEqprjy2vp6",
    rulebookLink:
      "https://drive.google.com/file/d/1-i1wxi5NPTZ8ghdhJvsO2pKzsWM4phw2/view?usp=drive_link",
  },

  {
    title: "Roborush",
    slug: "roborush",
    category: "Robotics",
    img: "/events/robotics/roborush.jpeg",
    desc: "Test the speed and agility of your robot in Roborush! Navigate through obstacles, race against time, and outperform competitors in this high-speed robotics challenge.",
    prize: "Exciting Prizes",
    venue: "Robotics Arena",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Rohit Aryan - b22ee017@nitm.ac.in",
      "Raunak Prabhakar - b23cs041@nitm.ac.in",
      "Parag Das - b23ee013@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/sxpV4RZj7V4FYKBU9",
    rulebookLink:
      "https://drive.google.com/file/d/1yQg0r_hFR-umltuEAkL_ZgkliSkWWQIt/view?usp=drive_link",
  },

  {
    title: "Drone Racing",
    slug: "drone-racing",
    category: "Robotics",
    img: "/events/robotics/droneracing.jpeg",
    desc: "Take flight in Drone Racing! Compete in an adrenaline-pumping race where precision flying and speed determine the winner. Navigate through challenging tracks and prove your piloting skills.",
    prize: "Exciting Prizes",
    venue: "Open Ground Arena",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Avinash Kumar Singh - b22cs012@nitm.ac.in",
      "Sanapala Rahul - b22ee010@nitm.ac.in",
      "Abhinav Hajong - b23ec006@nitm.ac.in",
      "Aastha Mishra - b23me005@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/oMmiF9nRAHffsH339",
    rulebookLink:
      "https://drive.google.com/file/d/1ECqsCr7cpqMxQM28zMgSod-QohICUxub/view?usp=drive_link",
  },

  {
    title: "Robodiction",
    slug: "robodiction",
    category: "Robotics",
    img: "/events/robotics/robodiction.jpg",
    desc: "A creative blend of robotics and communication, Robodiction challenges participants to interpret, build, or explain robotic concepts in an engaging way. Think fast, build smart, and communicate effectively!",
    prize: "Exciting Prizes",
    venue: "Robotics Arena",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Ankit Raj - b22ee005@nitm.ac.in",
      "B Palguna Rao - b22ee026@nitm.ac.in",
      "Gaurav Kumar Singh - b23ce006@nitm.ac.in",
      "Vignesh Patil - b23cs005@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/r4Y69TpQx38c99z38",
    rulebookLink:
      "https://drive.google.com/file/d/1PBs4oOepjEG_paH2FLmaFp44CViLoNpx/view?usp=drive_link",
  },

  {
    title: "Techstorm",
    slug: "techstorm",
    category: "Robotics",
    img: "/events/robotics/techstorm.jpeg",
    desc: "Enter Techstorm — a dynamic robotics event combining innovation, design, and technical challenges. Participants will tackle multiple problem statements, showcasing their engineering and problem-solving abilities.",
    prize: "Exciting Prizes",
    venue: "Robotics Arena",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Avinash Kumar Singh - b22cs012@nitm.ac.in",
      "Sanapala Rahul - b22ee010@nitm.ac.in",
      "Aman Kumar - b23cs038@nitm.ac.in",
      "Pradip Kumar Mondal - b23ec034@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/jbZKnAji7Kb5bqdU7",
    rulebookLink:
      "https://drive.google.com/file/d/1tkpUeQ8Mu5WX1SiwolJktvhTw1PYxMPO/view?usp=drive_link",
  },

  {
    title: "Autonomous Bot",
    slug: "autonomous-bot",
    category: "Robotics",
    img: "/events/robotics/autonomousbot.jpeg",
    desc: "Build intelligent machines in Autonomous Bot! Design robots capable of navigating and performing tasks without human intervention. This event tests your skills in automation, sensors, and AI integration.",
    prize: "Exciting Prizes",
    venue: "Robotics Arena",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Pankaj Saraswat - b22ec040@nitm.ac.in",
      "Purushottam Thakur - b23cs014@nitm.ac.in",
      "Chinagudaba Nikhil - b23me027@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/DNXHAvz7aTRiSsqy5",
    rulebookLink:
      "https://drive.google.com/file/d/1cTM_2d-QL0hBh3bRK02jOdRLFICalHLV/view?usp=drive_link",
  },
// Photography and fine arts
  {
    title: "Art Battle",
    slug: "art-battle",
    category: "Photography and Fine Arts",
    img: "/events/fine-arts/artbattle.jpeg",
    desc: "Unleash your creativity in Art Battle — a live art competition where imagination meets speed. Participants will create stunning artworks within a limited time based on surprise themes. It’s a battle of creativity, expression, and artistic skill where every stroke counts.",
    prize: "Exciting Prizes",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Satyam Singh - b23ce020@nitm.ac.in",
      "Md. Syed Ashraf Rafi - b23ec001@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/Z2URVYsRDUkdZWZT7",
    rulebookLink:
      "https://drive.google.com/file/d/1XDFC5izcnTcNwWpf9CtMUUFtq1T9POPX/view?usp=drive_link",
  },

  {
    title: "Photo Exhibition",
    slug: "photo-exhibition",
    category: "Photography and Fine Arts",
    img: "/events/fine-arts/photoexhibition.jpg",
    desc: "Capture moments, tell stories, and showcase your perspective through the Photo Exhibition. Participants can submit their best photographs based on given themes. From nature to urban life, every frame should reflect creativity, emotion, and storytelling.",
    prize: "Exciting Prizes",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Satyam Singh - b23ce020@nitm.ac.in",
      "Md. Syed Ashraf Rafi - b23ec001@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/JioRGRsd869p1v1B8",
    rulebookLink:
      "https://drive.google.com/file/d/1cNibOgyFf2xbmxrNQd-wI_iNT_aL0RBB/view?usp=drive_link",
  },
  // E-Cell
  {
    title: "Challenge on Green Technology",
    slug: "challenge-on-green-technology",
    category: "E-Cell",
    img: "/events/ecell/cogt.png",
    desc: "Innovate for a sustainable future in the Challenge on Green Technology! Participants are invited to propose and develop eco-friendly solutions that address environmental issues such as renewable energy, waste management, and sustainable living. Turn your ideas into impactful innovations that can shape a greener tomorrow.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Swarnim Suman - b24cs046@nitm.ac.in",
      " Nazia Sheikh - b23ce029@nitm.ac.in",
      "Anjali - b23me033@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/bQiRMVCT3yHMKKzm6",
    rulebookLink:
      "https://drive.google.com/file/d/1dB-SHlFNfjXZLVc9sAL_vYw8ZpiAVJHy/view?usp=drive_link",
  },

  {
    title: "Tech Challenge on Agriculture",
    slug: "tech-challenge-on-agriculture",
    category: "E-Cell",
    img: "/events/ecell/tcoa.jpg",
    desc: "Revolutionize agriculture with technology in the Tech Challenge on Agriculture! Participants will develop innovative solutions to improve farming efficiency, crop monitoring, irrigation systems, and supply chain management using modern technologies like IoT, AI, and data analytics.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Swarnim Suman - b24cs046@nitm.ac.in",
      " Nazia Sheikh - b23ce029@nitm.ac.in",
      "Anjali - b23me033@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/Aj5qier6oxJd4u5S8",
    rulebookLink:
      "https://drive.google.com/file/d/15iR7l16xBw0_No7t6ZXoRQkSvIXSDWdM/view?usp=drive_link",
  },
  // Design Club
  {
    title: "Doodle Art",
    slug: "doodle-art",
    category: "Design Club",
    img: "/events/design/doodle.jpg",
    desc: "Let your imagination flow freely in Doodle Art! This event challenges participants to create expressive and creative doodles based on given themes. Whether abstract or structured, your artwork should reflect originality, storytelling, and artistic flair.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Satyam Singh - b23ce020@nitm.ac.in",
      "Nazia Hasan Sheikh - b23ce029@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/BTK23XfNnwy3JFHC9",
    rulebookLink:
      "https://drive.google.com/file/d/1LEhtTnaiZMBZPWFlPB643qv0-y8ynAYX/view?usp=drive_link",
  },

  {
    title: "Canva Design Battle",
    slug: "canva-design-battle",
    category: "Design Club",
    img: "/events/design/canva.webp",
    desc: "Showcase your creativity in the Canva Design Battle! Participants will compete to create visually stunning designs using Canva within a limited time. From posters to social media creatives, design skills, aesthetics, and originality will decide the winner.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Satyam Singh - b23ce020@nitm.ac.in",
      "Nazia Hasan Sheikh - b23ce029@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/9pxgzoriT9REaqvV9",
    rulebookLink:
      "https://drive.google.com/file/d/16lQsRYKRrk0PD-rlIDmJHOn8T0sfLvLd/view?usp=drive_link",
  },
  // Astronomy Club
  {
    title: "Star Gazing",
    slug: "star-gazing",
    category: "Astronomy Club",
    img: "/events/astro/stargazing.webp",
    desc: "Explore the wonders of the night sky in Star Gazing! Participants will get a chance to observe celestial objects like planets, stars, and galaxies using telescopes. Guided by experts, this event offers a mesmerizing experience into the vast universe.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Ujjawal Jhajharia - b22ee007@nitm.ac.in",
      "Rounak Saha - b22cs008@nitm.ac.in",
      "Vishnu Kumar - b23ee014@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/CQFmY8BSYgbbgbJe6",
    rulebookLink:
      "https://drive.google.com/file/d/1ZI9UhXlhg37QRI2OBuHoRzaFtAL7LOUH/view?usp=drive_link",
  },

  {
    title: "Astro Quiz",
    slug: "astro-quiz",
    category: "Astronomy Club",
    img: "/events/astro/astroquiz.jpeg",
    desc: "Test your knowledge of the universe in the Astro Quiz! From planets and stars to black holes and space missions, this quiz will challenge your understanding of astronomy and astrophysics in a fun and competitive format.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Ujjawal Jhajharia - b22ee007@nitm.ac.in",
      "Rounak Saha - b22cs008@nitm.ac.in",
      "Vishnu Kumar - b23ee014@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/kUqNH44aJ8npNAs6A",
    rulebookLink: "https://drive.google.com/file/d/1VtZ5Q5DdZPGiJ0x7tQU1qzDr037kqO7Y/view?usp=drive_link",
  },

  {
    title: "Telescope Making",
    slug: "telescope-making",
    category: "Astronomy Club",
    img: "/events/astro/telescope.jpg",
    desc: "Build your own window to the universe in Telescope Making! Participants will learn the fundamentals of optics and assemble a working telescope. This hands-on event combines theory with practical skills for an enriching experience. Forms and Rulebook will be send via mail.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Ujjawal Jhajharia - b22ee007@nitm.ac.in",
      "Rounak Saha - b22cs008@nitm.ac.in",
      "Vishnu Kumar - b23ee014@nitm.ac.in",
    ],
    registerLink: "#",
    rulebookLink: "#",
  },
  // Dept Event
  {
    title: "The Hiring Panel(CS)",
    slug: "the-hiring-panel",
    category: "Dept",
    img: "/events/dept/thehiringpanel.jpg",
    desc: "Step into the shoes of both interviewer and candidate in this immersive hiring simulation. Test your technical knowledge, communication skills, and problem-solving ability while facing real-world interview scenarios. Whether you’re pitching solutions or evaluating them, this event prepares you for the corporate battlefield.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Rounak Saha - b22cs008@nitm.ac.in",
      "Shivam Thakur - b23cs021@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/aJMjBP3rsvYhbtTv5",
    rulebookLink: "https://drive.google.com/file/d/1mxPZgSk0rXcRmS04tKfANn60Rck8YB6p/view?usp=drive_link",
  },
  {
    title: "What's My Complexity(CS)",
    slug: "what-my-complexity",
    category: "Dept",
    img: "/events/dept/whatmycomplexity.jpeg",
    desc: "Think you can analyze code at a glance? Dive into the world of algorithms and sharpen your skills by determining time and space complexities. This event challenges your logical thinking and deep understanding of data structures and algorithm efficiency.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Rounak Saha - b22cs008@nitm.ac.in",
      "Shivam Thakur - b23cs021@nitm.ac.in",
    ],
    registerLink: "https://forms.gle/BpZo6DVyJu7Hr1Hy6",
    rulebookLink: "https://drive.google.com/file/d/1OYgrlUTfnSC0QEWPKqSoJ3cISe6PH4Nz/view?usp=drive_link",
  },
  {
    title: "Tech Pravah(ECE)",
    slug: "tech-pravah",
    category: "Dept",
    img: "/events/dept/techpravah.jpeg",
    desc: "Unleash your electronics expertise in this dynamic technical showdown. From core concepts to practical applications, Tech Pravah tests your understanding of circuits, signals, and systems through engaging and competitive rounds.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Medagam Manikanta Reddy - b22ec013@nitm.ac.in",
      "Pradip Kumar Mondal - b23ec034@nitm.ac.in",
      "Saurav - b23ec040@nitm.ac.in"
    ],
    registerLink: "https://forms.gle/Q19swJmcj73RVLDQ8",
    rulebookLink: "https://drive.google.com/file/d/1xqiFcNXUcyYpWSIQI7adpqmA65Ckrbul/view?usp=drive_link",
  },
  {
    title: "Electro Risc(ECE)",
    slug: "electro-risc",
    category: "Dept",
    img: "/events/dept/electrorisc.png",
    desc: "Get ready to explore the fundamentals of modern computing hardware with a focus on RISC architecture. This event blends theoretical knowledge with analytical thinking, pushing you to decode and optimize instruction-level operations.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Medagam Manikanta Reddy - b22ec013@nitm.ac.in",
      "Pradip Kumar Mondal - b23ec034@nitm.ac.in",
      "Saurav - b23ec040@nitm.ac.in"
    ],
    registerLink: "https://forms.gle/gQU4wA6THvrn5Rmk6",
    rulebookLink: "https://drive.google.com/file/d/1LvP3f-9kPuvZGklwJKJ9ykQpkuw2zORO/view?usp=drive_link",
  },
  {
    title: "Tech Vision(EE)",
    slug: "tech-vision",
    category: "Dept",
    img: "/events/dept/techvision.jpg",
    desc: "Step into the future of electrical engineering with challenges designed around innovation and practical problem-solving. Test your understanding of electrical systems, power, and emerging technologies in a highly competitive environment.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Mayank Mishra - b22ee030@nitm.ac.in",
      "Tinku Debbarma - b22ee020@nitm.ac.in",
      "Surabani Rani - b23ee018@nitm.ac.in"
    ],
    registerLink: "https://forms.gle/eeRYwP3NmtSLajAQ6",
    rulebookLink: "https://drive.google.com/file/d/1L57T2v5pw50U8eTBbkSKD2r8koSEvP6X/view?usp=drive_link",
  },
  {
    title: "Electro Quest(EE)",
    slug: "electro-quest",
    category: "Dept",
    img: "/events/dept/electroquest.jpeg",
    desc: "An electrifying quiz and problem-solving event that spans core electrical engineering concepts. From circuits to control systems, this quest will push your technical boundaries and reward your precision and speed.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Mayank Mishra - b22ee030@nitm.ac.in",
      "Tinku Debbarma - b22ee020@nitm.ac.in",
      "Surabani Rani - b23ee018@nitm.ac.in"
    ],
    registerLink: "https://forms.gle/AXe1YKxYFQz9DmJ8A",
    rulebookLink: "https://drive.google.com/file/d/1svYjqO64YzPK5bk0tjryZ3rJSKcngIuR/view?usp=drive_link",
  },
  {
    title: "Cycle Assembler(ME)",
    slug: "cycle-assembler",
    category: "Dept",
    img: "/events/dept/cycleassembler.jpeg",
    desc: "Put your mechanical engineering knowledge to the test through a series of exciting challenges. From design thinking to real-world applications, this event focuses on creativity, analytical skills, and engineering fundamentals.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Manisha Kumari - b22me020@nitm.ac.in",
      "Abhishek Kumar Chauhan - b23me026@nitm.ac.in",
      "Surabani Rani - b23me025@nitm.ac.in"
    ],
    registerLink: "https://forms.gle/WuRtUBd7LcpUVSN78",
    rulebookLink: "#",
  },
  {
    title: "Bascule Bridge(CE)",
    slug: "bascule-bridge",
    category: "Dept",
    img: "/events/dept/basculebridge.jpg",
    desc: "Design and simulate a functional bascule bridge while balancing structural efficiency and creativity. This event tests your understanding of civil engineering principles, mechanics, and real-world infrastructure design.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Satyam Singh - b22me020@nitm.ac.in",
      "Nazia Hasan Sheikh  - b23me026@nitm.ac.in",
      "Deisica Marbaniang - b23me025@nitm.ac.in"
    ],
    registerLink: "https://forms.gle/WuRtUBd7LcpUVSN78",
    rulebookLink: "https://drive.google.com/file/d/1O8nOMDmW4jtBZoOseX9_swRLHxiHeUAa/view?usp=drive_link",
  },
  {
    title: "Civiq(CE)",
    slug: "civiq",
    category: "Dept",
    img: "/events/dept/civiq.jpg",
    desc: "A civil engineering quiz and problem-solving competition that evaluates your knowledge of structures, materials, and environmental engineering. Compete with the best and prove your expertise in the civil domain.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Satyam Singh - b22me020@nitm.ac.in",
      "Nazia Hasan Sheikh  - b23me026@nitm.ac.in",
      "Deisica Marbaniang - b23me025@nitm.ac.in"
    ],
    registerLink: "https://forms.gle/RfZb4CyC2kHMmHdv9",
    rulebookLink: "https://drive.google.com/file/d/1SnLEEbShMHOa86ySheZ_6GGffNeys1FB/view?usp=drive_link",
  },
  {
    title: "Physics",
    slug: "physics",
    category: "Dept",
    img: "/events/dept/physics.jpeg",
    desc: "Explore the fascinating world of physics through conceptual challenges and problem-solving rounds. From mechanics to modern physics, this event is designed to test your understanding of fundamental principles.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      
    ],
    registerLink: "https://forms.gle/JnHQQCv1beh6romJ6",
    rulebookLink: "",
  },
  {
    title: "Maths",
    slug: "maths",
    category: "Dept",
    img: "/events/dept/maths.avif",
    desc: "Sharpen your analytical thinking and mathematical intuition in this challenging event. Solve intriguing problems that test your logic, speed, and depth of understanding across various mathematical domains.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Saismruti Sabat - s25ma009@nitm.ac.in"
    ],
    registerLink: "https://forms.gle/abZ3f8uCGCemNha49",
    rulebookLink: "",
  },
  {
    title: "Chemistry",
    slug: "chemistry",
    category: "Dept",
    img: "/events/dept/chemistry.jpeg",
    desc: "Dive into the world of reactions, compounds, and concepts in this chemistry-based competition. Test your theoretical knowledge and practical understanding through engaging and thought-provoking challenges.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      
    ],
    registerLink: "https://forms.gle/9Ey5KUaCXJV4w3zm8",
    rulebookLink: "#",
  },
  {
    title: "Box Cricket",
    slug: "box-cricket",
    category: "Fun Event",
    img: "/events/fun/boxcricket.avif",
    desc: "Get ready for high-energy action with Box Cricket – a fast-paced, thrilling version of cricket played in a compact arena. Form your squad, strategize your shots, and compete in quick matches where every run counts. Perfect for both cricket lovers and casual players, this event promises fun, excitement, and intense competition throughout!",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Gaurav Kumar Singh - b23ce006@nitm.ac.in",
      "Aman Mina - b23me031@nitm.ac.in"
    ],
    registerLink: "#",
    rulebookLink: "#",
  },
  {
    title: "Energize",
    slug: "energize",
    category: "Energy and Sustainability",
    img: "/events/energy/energize.jpg",
    desc: "Energize is a platform for innovative minds to explore solutions in energy and sustainability. Participants will tackle real-world challenges, propose creative ideas, and showcase their understanding of renewable energy systems. Whether you're passionate about green tech or future energy solutions, this event is your chance to shine.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Md Shams Tabrez Ansari - b22ee033@nitm.ac.in",
      "Diya Silvana Ritchil - b22ee001@nitm.ac.in"
    ],
    registerLink: "https://forms.gle/wS75Q4dikJzSGgxU9",
    rulebookLink: "https://drive.google.com/file/d/1518yPGGrIQkpUIja63khh4-US3YzKMW0/view?usp=drive_link",
  },
  {
    title: "Solar PV System Design",
    slug: "solar-pv-system-design",
    category: "Energy and Sustainability",
    img: "/events/energy/solar.jpeg",
    desc: "Dive into the world of renewable energy with the Solar PV System Design challenge. Participants will design efficient solar photovoltaic systems based on real-world requirements, focusing on optimization, cost-effectiveness, and sustainability. Ideal for tech enthusiasts eager to apply their knowledge to practical energy solutions.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Md Shams Tabrez Ansari - b22ee033@nitm.ac.in",
      "Imon Shahriar - b22ec001@nitm.ac.in"
    ],
    registerLink: "https://forms.gle/oUifo95DZDHQ16sd6",
    rulebookLink: "https://drive.google.com/file/d/1wDCZwbUuc82wcVsZrxFwzDigPGcYhdgI/view?usp=drive_link",
  },
  {
    title: "Ideathon 1.0",
    slug: "ideathon",
    category: "Energy and Sustainability",
    img: "/events/energy/ideathon.jpg",
    desc: "Ideathon 1.0 is a brainstorming battlefield where creativity meets problem-solving. Participants will pitch innovative ideas addressing energy and sustainability challenges. With limited time and boundless imagination, this event encourages participants to think big, innovate smart, and present impactful solutions.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Md Shams Tabrez Ansari - b22ee033@nitm.ac.in",
      "Aman Mina - b23me031@nitm.ac.in"
    ],
    registerLink: "https://forms.gle/JVbwNnmMM3LWQMfw6",
    rulebookLink: "https://drive.google.com/file/d/17GF_Z0FnEix_uIgNzsIhsyb6rKD6sWx0/view?usp=drive_link",
  },
  {
    title: "Enex Hunt",
    slug: "enex-hunt",
    category: "Energy and Sustainability",
    img: "/events/energy/enexhunt.avif",
    desc: "Enex Hunt is an exciting treasure hunt with an energy twist! Solve clues, complete challenges, and explore the campus while testing your knowledge of energy and sustainability concepts. Team up, think fast, and race against time to uncover the final treasure!",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Md Shams Tabrez Ansari - b22ee033@nitm.ac.in",
      "Manish Kumar - b23ce017@nitm.ac.in"
    ],
    registerLink: "https://forms.gle/jsadFwNJ7GhVxo8i8",
    rulebookLink: "https://drive.google.com/file/d/1vaOVEgkf5Dg2jemHVE91rxJcUcBUTP0q/view?usp=drive_link",
  },
   {
    title: "BGMI",
    slug: "bgmi",
    category: "Gaming",
    img: "/events/gaming/bgmi.webp",
    desc: "Featuring a massive ₹10,000 prize pool, this tournament is organized by Nodwin Gaming, bringing a professional esports experience to the campus. There is no direct registration or rulebook link at the moment—further details, including participation and match schedules, will be shared via email. Stay alert, drop in, and fight your way to victory!",
    prize: "10K",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Ankit Raj - b22ee005@nitm.ac.in",
      "Rohit Aryan - b22ee017@nitm.ac.in"
    ],
    registerLink: "#",
    rulebookLink: "#",
  },
  {
    title: "Valorant",
    slug: "valorant",
    category: "Gaming",
    img: "/events/gaming/valorant.jpg",
    desc: "Step into the tactical arena with Valorant, where precision, strategy, and teamwork define victory. Compete in intense 5v5 matches, master your agents, and outplay your opponents with sharp aim and smart coordination. Whether you're a clutch king or a strategic mastermind, this is your chance to dominate the battlefield and prove your squad’s supremacy.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Ankit Raj - b22ee005@nitm.ac.in",
      "Rohit Aryan - b22ee017@nitm.ac.in"
    ],
    registerLink: "https://forms.gle/RSRot9W2PqFYhvXw9",
    rulebookLink: "https://drive.google.com/file/d/1S-hYd4nZOwnp_0RQ0k9G5pvNZSAk4vHr/view?usp=drive_link",
  },
  {
    title: "Free Fire",
    slug: "free-fire",
    category: "Gaming",
    img: "/events/gaming/freefire.webp",
    desc: "Enter the fast-paced world of Free Fire, where survival is everything. Drop into action-packed matches, loot quickly, and outlast your enemies in a thrilling battle royale experience. With quick gameplay and intense encounters, every second counts—adapt, strategize, and fight your way to be the last one standing.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Ankit Raj - b22ee005@nitm.ac.in",
      "Rohit Aryan - b22ee017@nitm.ac.in"
    ],
    registerLink: "https://forms.gle/RZCVJe7AKK4tor5z6",
    rulebookLink: "https://drive.google.com/file/d/1acvmXYRtai8gNVYuLPZvqyLvOD7UaDlt/view?usp=drive_link",
  },
  {
    title: "Moba Legends",
    slug: "moba-legends",
    category: "Gaming",
    img: "/events/gaming/moba.jpg",
    desc: "Dive into the strategic battlefield of Moba Legends, where teamwork and tactics lead to victory. Choose your heroes, coordinate with your team, and outplay opponents in intense 5v5 clashes. From epic team fights to game-changing plays, this event tests your decision-making, coordination, and mastery of MOBA mechanics.",
    prize: "Exciting Prizes",
    deadline: "15th September 2025",
    venue: "NIT Campus",
    schedule: "9th April 2026 – 11th April 2026",
    contacts: [
      "Ankit Raj - b22ee005@nitm.ac.in",
      "Rohit Aryan - b22ee017@nitm.ac.in"
    ],
    registerLink: "https://forms.gle/DCxEP9efwjU75uBp7",
    rulebookLink: "https://drive.google.com/file/d/1JTUbq_JlWKU3I_-PZkgBVf-Aaq5mbmam/view?usp=drive_link",
  },
];

const eventsData = events.reduce((acc, ev) => {
  if (!acc[ev.category]) acc[ev.category] = [];
  acc[ev.category].push(ev);
  return acc;
}, {});

const teamData = {
  SAC: [
    {
      image: "/teams/sac/dean-studentwelfare.png",
      title: "Prof. Paonam Sudeep Mangang",
      subtitle: "Dean",
      handle: "Student's Welfare",
    },
    {
      image: "/teams/sac/sac-president.png",
      title: "Dr. Atanu Singha Roy",
      subtitle: "SAC",
      handle: "President",
    },
    {
      image: "/teams/sac/vp-technical.png",
      title: "Dr. Md Nur Alom",
      subtitle: "Technical",
      handle: "Vice-President",
    },
    {
      image: "/teams/sac/gs1.jpg",
      title: "Jitendra Dubey",
      subtitle: "General Secretary 1",
      handle: "Science & Technology",
    },
    {
      image: "/teams/sac/gs2.png",
      title: "Arush Raman",
      subtitle: "General Secretary 2",
      handle: "Science & Technology",
    },
    {
      image: "/teams/sac/member-1.png",
      title: "T.Bhanuprasad",
      subtitle: "Member 1",
      handle: "Science & Technology",
    },
    {
      image: "/teams/sac/member-2.png",
      title: "Raman Kumar Morya",
      subtitle: "Member 2",
      handle: "Science & Technology",
    },
  ],
  Dev: [
    {
      image: "/teams/dev/dev.JPG",
      title: "Kuldeep Chaudhary",
      subtitle: "Web Developer Head",
      handle: "b23ec019@nitm.ac.in",
    },
  ],
  Core: [
    {
      image: "/teams/core/core1.jpg",
      title: "Aman Singh Rathore",
      subtitle: "Head",
      handle: "b22cs017@nitm.ac.in",
    },
    {
      image: "/teams/core/core2.jpg",
      title: "Satyam Kumar Singh",
      subtitle: "Head",
      handle: "b22me026@nitm.ac.in",
    },
    {
      image: "/teams/core/core3.jpeg",
      title: "Sanapala Rahul",
      subtitle: "Head",
      handle: "b22ee010@nitm.ac.in",
    },
    {
      image: "/teams/core/core4.jpg",
      title: "Eshita Bhattacharjee",
      subtitle: "Cordinator",
      handle: "b23ee033@nitm.ac.in",
    },
    {
      image: "/teams/core/core5.jpg",
      title: "Austin Joel Dympep",
      subtitle: "Cordinator",
      handle: "b23cs035@nitm.ac.in",
    },
    {
      image: "/teams/core/core6.jpg",
      title: "Govindam kumar",
      subtitle: "Cordinator",
      handle: "b23cs035@nitm.ac.in",
    },
    {
      image: "/teams/core/core7.jpg",
      title: "Ippili Rupesh",
      subtitle: "Cordinator",
      handle: "b23ee011@nitm.ac.in",
    },
    {
      image: "/teams/core/core8.jpg",
      title: "Akshith Reddy",
      subtitle: "Member",
      handle: "b24ec020@nitm.ac.in",
    },
  ],
  "Sponsor and Marketing": [
    {
      image: "/teams/core/core1.jpg",
      title: "Aman Singh Rathore",
      subtitle: "Head",
      handle: "b22cs017@nitm.ac.in",
    },
    {
      image: "/teams/core/core2.jpg",
      title: "Satyam Kumar Singh",
      subtitle: "Head",
      handle: "b22me026@nitm.ac.in",
    },
    {
      image: "/teams/sponsor/sponsor1.JPG",
      title: "Arko Gupta",
      subtitle: "Co-Cordinator",
      handle: "b23ec031@nitm.ac.in",
    },
    {
      image: "/teams/sponsor/sponsor4.jpeg",
      title: "Antonia Charliza Lyngdoh",
      subtitle: "Co-Cordinator",
      handle: "b23ce024@nitm.ac.in",
    },
    {
      image: "/teams/sponsor/sponsor2.jpg",
      title: "Pettam Bhagirath",
      subtitle: "Member",
      handle: "b24ec025@nitm.ac.in",
    },
    {
      image: "/teams/sponsor/sponsor3.jpg",
      title: "Anshu Mohit",
      subtitle: "Member",
      handle: "b24cs045@nitm.ac.in",
    },
  ],
  "Publicity and Social Media": [
    {
      image: "/teams/publicity/publicity1.jpeg",
      title: "Debashish Nayak",
      subtitle: "Head",
      handle: "b22ec030@nitm.ac.in",
    },
    {
      image: "/teams/male-no-profile.webp",
      title: "Amar Chaudhary",
      subtitle: "Head",
      handle: "b24me015@nitm.ac.in",
    },
    {
      image: "/teams/publicity/publicity3.jpg",
      title: "Iahunlang Kharmynthon",
      subtitle: "Co-Cordinator",
      handle: "b23ce016@nitm.ac.in",
    },
    {
      image: "/teams/publicity/publicity4.jpg",
      title: "Kurra Nandini",
      subtitle: "Co-ordinator",
      handle: "b23ec018@nitm.ac.in",
    },
    {
      image: "/teams/publicity/publicity5.jpg",
      title: "Midasala Bhanu Vardhan Rao",
      subtitle: "Member",
      handle: "b24me022@nitm.ac.in",
    },
    {
      image: "/teams/publicity/publicity6.jpeg",
      title: "Sumit Kumar",
      subtitle: "Member",
      handle: "b24cs049@nitm.ac.in",
    },
  ],
  Robotics: [
    {
      image: "/teams/robotics/robotics1.jpg",
      title: "Avinash Kumar Singh",
      subtitle: "Convenor",
      handle: "b22cs012@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics2.jpg",
      title: "Pankaj Saraswat",
      subtitle: "Convenor",
      handle: "b22ec040@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics3.png",
      title: "Shivam Kumar",
      subtitle: "Head",
      handle: "b22me011@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics4.jpeg",
      title: "Rahul Kumar",
      subtitle: "Head",
      handle: "b22ce020@nitm.ac.in",
    },
    {
      image: "/teams/robotics/robotics5.jpg",
      title: "Aditya Kumar Pandey",
      subtitle: "Head",
      handle: "b22me018@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics6.jpg",
      title: "Himanshu Kumar Jha",
      subtitle: "Head",
      handle: "b22me027@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics7.jpeg",
      title: "Debashish Nayak",
      subtitle: "Head",
      handle: "b22ec030@nitm.ac.in",
    },
    {
      image: "/teams/robotics/robotics8.jpeg",
      title: "Sanapala Rahul",
      subtitle: "Head",
      handle: "b22ee010@nitm.ac.in",
    },
    {
      image: "/teams/robotics/robotics9.jpg",
      title: "Rohit Aryan",
      subtitle: "Head",
      handle: "b22ee017@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics10.jpg",
      title: "Ankit Raj",
      subtitle: "Head",
      handle: "b22ee005@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics11.jpg",
      title: "B Palguna Rao",
      subtitle: "Head",
      handle: "b22ee026@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics12.jpg",
      title: "Akash Shah",
      subtitle: "Coordinator",
      handle: "b23me008@nitm.ac.in",
    },
    {
      image: "/teams/robotics/robotics13.jpg",
      title: "Sachin Chaurasia",
      subtitle: "Coordinator",
      handle: "b23ee010@nitm.ac.in",
    },
    {
      image: "/teams/robotics/robotics14.jpg",
      title: "Vishnu Kumar",
      subtitle: "Coordinator",
      handle: "b23ee014@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics15.jpeg",
      title: "Akshaj Sunil",
      subtitle: "Coordinator",
      handle: "b23me020@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics16.png",
      title: "Adharsh Barman",
      subtitle: "Coordinator",
      handle: "b23ee005@nitm.ac.in",
    },
    {
      image: "/teams/robotics/robotics17.webp",
      title: "Saksham Singhania",
      subtitle: "Coordinator",
      handle: "b23ce026@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics18.png",
      title: "Raunak Prabhakar",
      subtitle: "Coordinator)",
      handle: "b23cs041@nitm.ac.in",
    },
    {
      image: "/teams/robotics/robotics19.jpeg",
      title: "Parag Das",
      subtitle: "Coordinator",
      handle: "b23ee013@nitm.ac.in",
    },
    {
      image: "/teams/robotics/robotics20.png",
      title: "Abhinav Hajong",
      subtitle: "Coordinator",
      handle: "b23ec006@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics21.jpg",
      title: "Aastha Mishra",
      subtitle: "Coordinator",
      handle: "b23me005@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics22.jpg",
      title: "Gaurav Kumar Singh",
      subtitle: "Coordinator",
      handle: "b23ce006@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics23.JPG",
      title: "Vignesh Patil",
      subtitle: "Coordinator",
      handle: "b23ce005@nitm.ac.in",
    },
    {
      image: "/teams/robotics/robotics24.jpg",
      title: "Aman Kumar",
      subtitle: "Coordinator",
      handle: "b23cs038@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics25.jpg",
      title: "Pradip Kumar Mondal",
      subtitle: "Coordinator",
      handle: "b23ec034@nitm.ac.in",
    },
    {
      image: "/teams/robotics/robotics26.jpg",
      title: "Purushottam Thakur",
      subtitle: "Coordinator",
      handle: "b23cs014@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics27.jpg",
      title: "Chinagudaba Nikhil",
      subtitle: "Coordinator",
      handle: "b23me027@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics28.jpg",
      title: "Shreya Raj",
      subtitle: "Member",
      handle: "b24ce014@nitm.ac.in",
    },
    {
      image: "/teams/robotics/robotics29.jpg",
      title: "Ankita Singh",
      subtitle: "Member",
      handle: "b24cs018@nitm.ac.in",
    },
    {
      image: "/teams/robotics/robotics30.jpg",
      title: "Abhishek Jaiswal",
      subtitle: "Member",
      handle: "b24ee001@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics31.jpg",
      title: "Bibhuti Mishra",
      subtitle: "Member",
      handle: "b24cs016@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics32.jpg",
      title: "Sonam Kumari",
      subtitle: "Member",
      handle: "b24cs047@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics33.jpg",
      title: "Probhos Mandal",
      subtitle: "Member",
      handle: "b24ce010@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics34.jpeg",
      title: "Sanjog Singh",
      subtitle: "Member",
      handle: "b24ec005@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics35.webp",
      title: "Rahul Kumar",
      subtitle: "Member",
      handle: "b24ec023@nitm.ac.in",
    },
    {
      image: "/teams/robotics/robotics36.JPG",
      title: "Anindya Nandy Arnab",
      subtitle: "Member",
      handle: "b24ec032@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics37.jpg",
      title: "Md Kashif Iqbal",
      subtitle: "Member",
      handle: "b24ec007@nitm.ac.in",
    }, 
    {
      image: "/teams/male-no-profile.webp",
      title: "Kunal Das",
      subtitle: "Member",
      handle: "b24me003@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics39.jpeg",
      title: "Rahul Prasad",
      subtitle: "Member",
      handle: "b24ee004@nitm.ac.in",
    },
    {
      image: "/teams/robotics/robotics40.jpg",
      title: "Ayush Kumar",
      subtitle: "Member",
      handle: "b24me030@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics41.jpg",
      title: "Akash Hajong",
      subtitle: "Member",
      handle: "b24me001@nitm.ac.in",
    },
    {
      image: "/teams/robotics/robotics42.jpg",
      title: "Rohit Das",
      subtitle: "Member",
      handle: "b24cs012@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics43.jpg",
      title: "Anshu Mohit",
      subtitle: "Member",
      handle: "b24cs045@nitm.ac.in",
    }, 
    {
      image: "/teams/robotics/robotics44.jpg",
      title: "Divyashakti",
      subtitle: "Member",
      handle: "b24ee008@nitm.ac.in",
    },
    {
      image: "/teams/robotics/robotics45.png",
      title: "Bhabhisya Paudel",
      subtitle: "Member",
      handle: "b24cs033@nitm.ac.in",
    }, 
  ],
  Coding: [
    {
      image: "/teams/coding/coding1.jpg",
      title: "Karipireddy Surya Teja Gopal Reddy",
      subtitle: "Convenor",
      handle: "b22cs022@nitm.ac.in",
    },
    {
      image: "/teams/coding/coding2.JPG",
      title: "Chuncha Hemchand",
      subtitle: "Co-Convenor",
      handle: "b23cs020@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding3.jpeg",
      title: "Mrinmoy Maji",
      subtitle: "Head",
      handle: "b22cs036@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding4.jpeg",
      title: "Manish Prasad Gupta",
      subtitle: "Head",
      handle: "b22cs007@nitm.ac.in",
    },
    {
      image: "/teams/coding/coding5.png",
      title: "Prem Kumar Gupta",
      subtitle: "Head",
      handle: "b22cs026@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding6.jpg",
      title: "T Vikram Rathod",
      subtitle: "Head",
      handle: "b22cs033@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding7.png",
      title: "Satyajeet Rai",
      subtitle: "Head",
      handle: "b22ec021@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding8.png",
      title: "Ankit Raj",
      subtitle: "Co-ordinator",
      handle: "b23ec012@nitm.ac.in",
    },
    {
      image: "/teams/male-no-profile.webp",
      title: "Abhay Kumar",
      subtitle: "Co-ordinator",
      handle: "b23ec022@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding10.jpg",
      title: "Austin Joel Dympep",
      subtitle: "Co-ordinator",
      handle: "b23cs035@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding11.jpg",
      title: "Arunoday Tiwari",
      subtitle: "Co-ordinator",
      handle: "b23ec009@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding12.jpg",
      title: "Shashank Umar Vaishy",
      subtitle: "Co-ordinator",
      handle: "b23cs019@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding13.jpg",
      title: "Charity Rymbai",
      subtitle: "Co-ordinator",
      handle: "b23me010@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding14.png",
      title: "Aryan Raj",
      subtitle: "Co-ordinator",
      handle: "b23ec042@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding15.jpeg",
      title: "Khushi Kumari",
      subtitle: "Co-ordinator",
      handle: "b23ec008@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding16.png",
      title: "Jishnu Duhan",
      subtitle: "Co-ordinator",
      handle: "b23cs037@nitm.ac.in",
    },
    {
      image: "/teams/coding/coding17.jpeg",
      title: "Ayush Kumar Singh",
      subtitle: "Co-ordinator",
      handle: "b23ec003@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding18.jpg",
      title: "Rohit Das",
      subtitle: "Member",
      handle: "b24cs012@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding19.png",
      title: "Rishab Mankotia Synjri",
      subtitle: "Member",
      handle: "b24cs006@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding20.webp",
      title: "Shaik Thanveer",
      subtitle: "Member",
      handle: "b24cs035@nitm.ac.in",
    },
    {
      image: "/teams/male-no-profile.webp",
      title: "Kurva Hemanth",
      subtitle: "Member",
      handle: "b24cs008@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding22.jpg",
      title: "Sonam Kumari",
      subtitle: "Member",
      handle: "b24cs047@gmail.com",
    }, 
    {
      image: "/teams/male-no-profile.webp",
      title: "Mohit Kumar",
      subtitle: "Member",
      handle: "b24cs001@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding24.jpeg",
      title: "Avishek Sah",
      subtitle: "Member",
      handle: "b24cs031@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding25.jpg",
      title: "Kunjana Panthy",
      subtitle: "Member",
      handle: "b24cs036@nitm.ac.in",
    },
    {
      image: "/teams/coding/coding26.jpg",
      title: "Kunal",
      subtitle: "Member",
      handle: "b24cs020@nitm.ac.in",
    },
    {
      image: "/teams/male-no-profile.webp",
      title: "Pasupu Reddy Shyameswar",
      subtitle: "Member",
      handle: "b24cs037@nitm.ac.in",

    }, 
    {
      image: "/teams/coding/coding28.jpeg",
      title: "Prathipati Dhanush",
      subtitle: "Member",
      handle: "b24cs048@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding29.png",
      title: "Rahul Das",
      subtitle: "Member",
      handle: "b24cs044@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding30.jpeg",
      title: "Nathaniel Kharsynniang",
      subtitle: "Member",
      handle: "b24cs027@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding31.jpg",
      title: "Rhythm Bhetwal",
      subtitle: "Member",
      handle: "b24cs038@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding32.jpeg",
      title: "Akash Malaker",
      subtitle: "Member",
      handle: "b24cs042@nitm.ac.in",
    },
    {
      image: "/teams/coding/coding32.jpg",
      title: "Dharavath Drushyanth",
      subtitle: "Member",
      handle: "b24cs026@nitm.ac.in",
    }, 
    {
      image: "/teams/coding/coding33.jpg",
      title: "Anshu Mohit",
      subtitle: "Member",
      handle: "b24cs045@nitm.ac.in",
    }, 
  ],
  "Task Force Club": [
    {
      image: "/teams/taskforce/taskforce3.jpg",
      title: "Charagundla Sai Laxman",
      subtitle: "Head",
      handle: "b22ec036@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/male-no-profile.webp",
      title: "Jitta Chandra Sekhar",
      subtitle: "Convenor",
      handle: "b23me013@nitm.ac.in",
    }, // Pink
    {
      image: "/teams/male-no-profile.webp",
      title: "Podugu Ashrith",
      subtitle: "Convenor",
      handle: "b23ec013@nitm.ac.in",
    }, 
    {
      image: "/teams/taskforce/taskforce4.jpg",
      title: "Gourav Kumar",
      subtitle: "Co-ordinator",
      handle: "b23me018@nitm.ac.in",
    }, // Pink
    {
      image: "/teams/taskforce/taskforce5.jpg",
      title: "Nishu Lamba",
      subtitle: "Member",
      handle: "b24me028@nitm.ac.in",
    }, // Pink
    {
      image: "/teams/taskforce/taskforce6.png",
      title: "Aditya Kumar Thakur",
      subtitle: "Member",
      handle: "b24ec035@nitm.ac.in",
    }, // Pink
  ],
  "Dance & Drama": [
    {
      image: "/teams/dance/dance1.jpg",
      title: "Sandra Sravani",
      subtitle: "Convenor",
      handle: "b22me009@nitm.ac.in",
    },
    {
      image: "/teams/dance/dance2.jpeg",
      title: "B Palguna Rao",
      subtitle: "Convenor",
      handle: "b22ee026@nitm.ac.in",

    },
    {
      image: "/teams/dance/dance3.jpg",
      title: "T Sanjana",
      subtitle: "Coordinator",
      handle: "b23ee026@nitm.ac.in",

    },
    {
      image: "/teams/male-no-profile.webp",
      title: "M Sreekar Prasad",
      subtitle: "Coordinator",
      handle: "b23ec023@nitm.ac.in",
 
    },
  ],
  "Photography and fine arts": [
    {
      image: "/teams/art/art1.png",
      title: "Satyam Singh",
      subtitle: "Convenor",
      handle: "b23ce020@nitm.ac.in",
    },
    {
      image: "/teams/art/art2.jpeg",
      title: "Md. Syed Ashraf Rafi",
      subtitle: "Convenor",
      handle: "b23ec001@nitm.ac.in",
    },
    {
      image: "/teams/art/art3.jpg",
      title: "Aditya Tripathi",
      subtitle: "Member",
      handle: "b24ce028@nitm.ac.in",
    },
    {
      image: "/teams/art/art4.png",
      title: "Harish Meena",
      subtitle: "Member",
      handle: "b24ce027@nitm.ac.in",
    },
  ],
  "E-Cell": [
    {
      image: "/teams/ecell/ecell1.jpeg",
      title: "Swarnim Suman",
      subtitle: "Convenor",
      handle: "b24cs046@nitm.ac.in",
    },
    {
      image: "/teams/ecell/ecell2.jpg",
      title: "Nazia Sheikh",
      subtitle: "Coordinator",
      handle: "b23ce029@nitm.ac.in",
    },
    {
      image: "/teams/female-no-profile.webp",
      title: "Anjali",
      subtitle: "Coordinator",
      handle: "b23me033@nitm.ac.in",
    },
    {
      image: "/teams/ecell/ecell4.jpg",
      title: "Ledonki Bevan Laloo",
      subtitle: "Coordinator",
      handle: "b23me030@nitm.ac.in",
    },
    {
      image: "/teams/male-no-profile.webp",
      title: "Alfred L. Pautu",
      subtitle: "Coordinator",
      handle: "b23me003@nitm.ac.in",

    },
    {
      image: "/teams/male-no-profile.webp",
      title: "Abhay Mishra",
      subtitle: "Member",
      handle: "b24ee022@nitm.ac.in",
    },
    {
      image: "/teams/ecell/ecell7.jpg",
      title: "Akshith Reddy",
      subtitle: "Member",
      handle: "b24ec020@nitm.ac.in",
    },
  ],
  "Energy and Sustainability Club": [
    {
      image: "/teams/energy/energy1.jpg",
      title: "Md Shams Tabrez Ansari",
      subtitle: "Convenor",
      handle: "b22ee033@nitm.ac.in",
    },
    {
      image: "/teams/energy/energy2.jpeg",
      title: "Diya Silvana Ritchil",
      subtitle: "Coordinator",
      handle: "b22ee001@nitm.ac.in",
    },
    {
      image: "/teams/energy/energy3.png",
      title: "Imon Shahriar",
      subtitle: "Coordinator",
      handle: "b22ec001@nitm.ac.in",
    },
    {
      image: "/teams/energy/energy4.jpg",
      title: "Aman Mina",
      subtitle: "Coordinator",
      handle: "b23me031@nitm.ac.in",
    },
    {
      image: "/teams/energy/energy5.jpg",
      title: "Manish Kumar",
      subtitle: "Coordinator",
      handle: "b23ce017@nitm.ac.in",
    },
    {
      image: "/teams/energy/energy6.jpeg",
      title: "Swarnim Suman",
      subtitle: "Member",
      handle: "b24cs046@nitm.ac.in",
    },
    {
      image: "/teams/energy/energy7.jpeg",
      title: "Sanjog Singh",
      subtitle: "Member",
      handle: "b24ec005@nitm.ac.in",
    },
    {
      image: "/teams/energy/energy9.jpg",
      title: "Ayush Kumar",
      subtitle: "Member",
      handle: "b24me030@nitm.ac.in",
    },
    {
      image: "/teams/energy/energy8.webp",
      title: "Rahul Kumar",
      subtitle: "Member",
      handle: "b24ec023@nitm.ac.in",
    },
  ],
  "Design Club": [
    {
      image: "/teams/design/design1.png",
      title: "Satyam Singh",
      subtitle: "Convenor",
      handle: "b23ce020@nitm.ac.in",
    },
    {
      image: "/teams/design/design2.jpg",
      title: "Nazia Hasan Sheikh",
      subtitle: "Convenor",
      handle: "b23ce029@nitm.ac.in",
    },
    {
      image: "/teams/design/design3.jpeg",
      title: "Poulomi Das",
      subtitle: "Member",
      handle: "b24me004@nitm.ac.in",
    },
    {
      image: "/teams/design/design4.jpg",
      title: "Bhawani Shankar",
      subtitle: "Member",
      handle: "b24ee020@nitm.ac.in",
    },
  ],
  "Astronomy Club": [
    {
      image: "/teams/astronomy/astronomy1.jpg",
      title: "Ujjawal Jhajharia",
      subtitle: "Convenor",
      handle: "b22ee007@nitm.ac.in",
    },
    {
      image: "/teams/astronomy/astronomy2.png",
      title: "Rounak Saha",
      subtitle: "Convenor",
      handle: "b22cs008@nitm.ac.in",
    },
    {
      image: "/teams/astronomy/astronomy3.jpg",
      title: "Vishnu Kumar",
      subtitle: "Coordinator",
      handle: "b23ee014@nitm.ac.in",
    },
  ],
  Departmental: [
    {
      image: "/teams/departmental/departmental1.png",
      title: "Rounak Saha",
      subtitle: "Head(CSE)",
      handle: "b22cs008@nitm.ac.in",
    },
    {
      image: "/teams/departmental/departmental2.jpeg",
      title: "Medagam Manikanta Reddy",
      subtitle: "Head(ECE)",
      handle: "b22ec013@nitm.ac.in",
    },
    {
      image: "/teams/departmental/departmental3.jpg",
      title: "Mayank Mishra",
      subtitle: "Head(EEE)",
      handle: "b22ee030@nitm.ac.in",
    },
    {
      image: "/teams/departmental/departmental4.jpeg",
      title: "Tinku Debbarma",
      subtitle: "Head(EEE)",
      handle: "b22ee020@nitm.ac.in",
    },
    {
      image: "/teams/departmental/departmental5.jpg",
      title: "Manisha Kumari",
      subtitle: "Head(ME)",
      handle: "b22me020@nitm.ac.in",
    },
    {
      image: "/teams/departmental/departmental6.jpg",
      title: "Saismruti Sabat",
      subtitle: "Head(Math)",
      handle: "s25ma009@nitm.ac.in",
    },
    {
      image: "/teams/departmental/departmental7.JPG",
      title: "Shivam Thakur",
      subtitle: "Coordinator(CSE)",
      handle: "b23cs021@nitm.ac.in",
    },
    {
      image: "/teams/departmental/departmental8.jpg",
      title: "Pradip Kumar Mondal",
      subtitle: "Coordinator(ECE)",
      handle: "b23ec034@nitm.ac.in",
    },
    {
      image: "/teams/departmental/departmental9.jpg",
      title: "Saurav Kumar",
      subtitle: "Coordinator(ECE)",
      handle: "b23ec040@nitm.ac.in",
    },
    {
      image: "/teams/female-no-profile.webp",
      title: "Surabani Rani",
      subtitle: "Coordinator(EE)",
      handle: "b23ee018@nitm.ac.in",
    },
    {
      image: "/teams/departmental/departmental11.png",
      title: "Abhishek Kumar Chauhan",
      subtitle: "Coordinator(ME)",
      handle: "b23me026@nitm.ac.in",
    },
    {
      image: "/teams/departmental/departmental12.jpg",
      title: "John Nelvidson Marwein",
      subtitle: "Coordinator(ME)",
      handle: "b23me025@nitm.ac.in",
    },
    {
      image: "/teams/departmental/departmental13.png",
      title: "Satyam Singh",
      subtitle: "Coordinator(CE)",
      handle: "b23ce020@nitm.ac.in",
    },
    {
      image: "/teams/departmental/departmental14.jpg",
      title: "Nazia Hasan Sheikh",
      subtitle: "Coordinator(CE)",
      handle: "b23ce029@nitm.ac.in",
    },
    {
      image: "/teams/departmental/departmental16.jpg",
      title: "DEISICA MARBANIANG",
      subtitle: "Coordinator(CE)",
      handle: "b23ce008@nitm.ac.in",
    },
    {
      image: "/teams/departmental/departmental15.jpg",
      title: "Md Kashif",
      subtitle: "Member(ECE)",
      handle: "b24ec007@nitm.ac.in",
    },
  ],
  Design: [
    {
      image: "/teams/male-no-profile.webp",
      title: "Botu Varun",
      subtitle: "Head",
      handle: "b22ec008@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/male-no-profile.webp",
      title: "L Komune",
      subtitle: "Head",
      handle: "b22ce016@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/male-no-profile.webp",
      title: "Tiyangsen Lemtor",
      subtitle: "Head",
      handle: "b22me013@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/designteam/designteam4.jpg",
      title: "Ritik Kumar",
      subtitle: "Coordinator",
      handle: "b23me014@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/designteam/designteam5.png",
      title: "Satyam Singh",
      subtitle: "Coordinator",
      handle: "b23ce020@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/designteam/designteam6.jpg",
      title: "Priya Saha",
      subtitle: "Member",
      handle: "b24cs023@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/designteam/designteam7.jpg",
      title: "Bhawani Shankar",
      subtitle: "Member",
      handle: "b24ee020@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/designteam/designteam8.jpg",
      title: "Probhas Mondal",
      subtitle: "Member",
      handle: "b24ce010@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/designteam/designteam9.jpeg",
      title: "Poulomi Das",
      subtitle: "Member",
      handle: "b24me004@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/designteam/designteam10.jpg",
      title: "Midasala Bhanu Vardhan Rao",
      subtitle: "Member",
      handle: "b24me022@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/designteam/designteam11.jpg",
      title: "Deepak",
      subtitle: "Member",
      handle: "b24ce007@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/designteam/designteam12.jpg",
      title: "Md Kashif",
      subtitle: "Member",
      handle: "b24ec007@nitm.ac.in",
      borderColor: "#EC4899",
    },
  ],
  Volunteer: [
    {
      image: "/teams/volunteer/volunteer1.jpeg",
      title: "Debashish Nayak",
      subtitle: "Head",
      handle: "b22ec030@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/volunteer/volunteer2.jpg",
      title: "Kurra Nandini",
      subtitle: "Coordinator",
      handle: "b23ec018@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/volunteer/volunteer3.png",
      title: "Abhinav Hajong",
      subtitle: "Coordinator",
      handle: "b23ec006@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/male-no-profile.webp",
      title: "Dai",
      subtitle: "Coordinator",
      handle: "b24ce012@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/volunteer/volunteer5.jpg",
      title: "Valluri Venkata Mohan",
      subtitle: "Coordinator",
      handle: "b24ec030@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/volunteer/volunteer6.jpg",
      title: "Deepak",
      subtitle: "Member",
      handle: "b24ce007@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/volunteer/volunteer7.jpg",
      title: "Bhawani Shankar",
      subtitle: "Member",
      handle: "b24ee020@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/volunteer/volunteer8.jpg",
      title: "Aman Kumar Jaiswal",
      subtitle: "Member",
      handle: "b24ee029@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/volunteer/volunteer9.jpg",
      title: "Shreya Raj",
      subtitle: "Member",
      handle: "b24ce014@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/volunteer/volunteer10.jpg",
      title: "Amit Kuri",
      subtitle: "Member",
      handle: "b24me029@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/volunteer/volunteer11.jpeg",
      title: "Sumit Kumar",
      subtitle: "Member",
      handle: "b24cs049@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/volunteer/volunteer12.jpeg",
      title: "Nathaniel Kharsynniang",
      subtitle: "Member",
      handle: "b24cs027@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/volunteer/volunteer13.png",
      title: "Aditya Kumar Thakur",
      subtitle: "Member",
      handle: "b24ec035@nitm.ac.in",
      borderColor: "#EC4899",
    },
  ],
  Gaming: [
    {
      image: "/teams/robotics/robotics10.jpg",
      title: "Ankit Raj",
      subtitle: "Head",
      handle: "b22ee005@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/gaming/gaming2.jpg",
      title: "Rohit Aryan",
      subtitle: "Head",
      handle: "b22ee017@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/gaming/gaming3.jpg",
      title: "Ledonki Bevan Laloo ",
      subtitle: "Co-Coordinator",
      handle: "b23me030@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/gaming/gaming4.png",
      title: "Abhinav Hajong",
      subtitle: "Co-Coordinator",
      handle: "b23ec006@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/gaming/gaming5.jpg",
      title: "Aibansansame Kharbanni",
      subtitle: "Co-Coordinator",
      handle: "b23cs024@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/gaming/gaming6.jpg",
      title: "Amit Kuri",
      subtitle: "Member",
      handle: "b24me029@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/gaming/gaming7.jpg",
      title: "Rohit Das",
      subtitle: "Member",
      handle: " b24cs012@nitm.ac.in",
      borderColor: "#EC4899",
    },
  ],
  Management: [
    {
      image: "/teams/management/management1.jpeg",
      title: "B Vedant",
      subtitle: "Head(Stage Management)",
      handle: "b22ee012@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/management/management2.jpg",
      title: "Bojha Jaswanth",
      subtitle: "Head(Event Management)",
      handle: "b22me007@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/management/management3.jpg",
      title: "Sheikh Nabeel",
      subtitle: "Head(Event Management)",
      handle: "b22ee025@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/management/management4.jpg",
      title: "Winson Suchiang",
      subtitle: "Head(Public Relations)",
      handle: "b22ec006@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/management/management5.jpg",
      title: "Aman Mina",
      subtitle: "Co-Coordinator(Stage Management)",
      handle: "b23me031@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/management/management6.jpg",
      title: "Nazia Hasan Sheikh",
      subtitle: "Co-Coordinator(Stage Management)",
      handle: "b23ce029@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/management/management7.jpg",
      title: "Saurav Kumar",
      subtitle: "Co-Coordinator(Event Management)",
      handle: "b23ec040@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/management/management8.jpg",
      title: "Bandla venkata Bharath chandra",
      subtitle: "Co-Coordinator(Event Management)",
      handle: "",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/management/management8.jpg",
      title: "Purushottam Thakur",
      subtitle: "Co-Coordinator(Event Management)",
      handle: "b23cs014@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/management/management9.jpg",
      title: "Manish Kumar",
      subtitle: "Co-Coordinator(Public Relations)",
      handle: "b23ce017@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/management/management10.jpg",
      title: "Kunal",
      subtitle: "Member(Stage Management)",
      handle: "b24cs020@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/management/management11.jpeg",
      title: "Sumit Kumar",
      subtitle: "Member(Stage Management)",
      handle: "b24cs049@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/management/management12.jpg",
      title: "Amit Kumar",
      subtitle: "Member(Event Management)",
      handle: "b24ee025@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/male-no-profile.webp",
      title: "Shreyas Sharma",
      subtitle: "Member(Public Relations)",
      handle: "b24ee016@nitm.ac.in",
      borderColor: "#EC4899",
    },
  ],
  Hospitality: [
    {
      image: "/teams/hospitality/hospitality1.jpg",
      title: "Vanyza Lyngshiang",
      subtitle: "Head",
      handle: "b22ee008@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/hospitality/hospitality2.png",
      title: "Abhishek Kumar Chauhan",
      subtitle: "Co-Coordinator",
      handle: "b23me026@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/hospitality/hospitality3.jpg",
      title: "Sanjeev Gupta",
      subtitle: "Co-Coordinator",
      handle: "b23me004@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/hospitality/hospitality4.jpeg",
      title: "Nathaniel Kharsynniang",
      subtitle: "Member",
      handle: "b24cs027@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/hospitality/hospitality5.png",
      title: "Aditya Kumar Thakur",
      subtitle: "Member",
      handle: "b24ec035@nitm.ac.in",
      borderColor: "#EC4899",
    },
  ],
  "Food Committee": [
    {
      image: "/teams/food/food1.jpg",
      title: "Ashirbad Raj Arya",
      subtitle: "Head",
      handle: "b22ec009@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/food/food2.jpeg",
      title: "B Palguna Rao",
      subtitle: "Head",
      handle: "b22ee026@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/food/food3.JPG",
      title: "Kuldeep Chaudhary",
      subtitle: "Coordinator",
      handle: "b23ec019@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/food/food4.jpg",
      title: "Ritik Kumar",
      subtitle: "Coordinator",
      handle: "b23me014@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/food/food5.jpg",
      title: "Minalish Hajong",
      subtitle: "Member",
      handle: "b24ec011@nitm.ac.in",
      borderColor: "#EC4899",
    },
    {
      image: "/teams/food/food6.jpg",
      title: "Aman Kumar Jaiswal",
      subtitle: "Member",
      handle: "b24ee029@nitm.ac.in",
      borderColor: "#EC4899",
    },
  ],
};

export { navLinks, eventsData, events, teamData };
